habitat.truck.spawn.period.millis=200
habitat.truck.spawn.probability=0.7

habitat.car.spawn.period.millis=300
habitat.car.spawn.probability=0.5

vehicle.relative.size=0.05
vehicle.image.size=64

vehicle.images.base.path=/images/vehicles
vehicle.images.cars.path=/images/vehicles/cars
vehicle.images.trucks.path=/images/vehicles/trucks
vehicle.image.extensions=.png,.jpg,.jpeg